# Generated by Django 2.2.6 on 2019-10-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserScheduleDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(blank=True, max_length=8)),
                ('time', models.CharField(blank=True, max_length=50)),
                ('A', models.CharField(blank=True, max_length=50)),
                ('B', models.CharField(blank=True, max_length=50)),
                ('C', models.CharField(blank=True, max_length=50)),
                ('D', models.CharField(blank=True, max_length=50)),
                ('E', models.CharField(blank=True, max_length=50)),
                ('F', models.CharField(blank=True, max_length=50)),
                ('time50', models.CharField(blank=True, max_length=50)),
                ('A50', models.CharField(blank=True, max_length=50)),
                ('B50', models.CharField(blank=True, max_length=50)),
                ('C50', models.CharField(blank=True, max_length=50)),
                ('D50', models.CharField(blank=True, max_length=50)),
                ('E50', models.CharField(blank=True, max_length=50)),
                ('F50', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
